name: WordPress Coding Standard Check

on: pull_request


jobs:
  phpcs:
      name: VIPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: VIPCS check
          uses: 10up/wpcs-action@stable
          with:
            standard: 'WordPress-VIP-Go'
            use_local_config: 'true'
            extra_args: '--report-json=./phpcs.json'
            paths: ${{ github.event.pull_request.changed_files }}